### ISSUE TITLE
unimplemented "get_template_contents" function

### ISSUE THREAD

**Issue by arfar** [programble/scraper#11]
Hi there

For a small personal project I'm working on I'd like to extract the recipe on [this recipe website](https://www.foodnetwork.com/recipes/alton-brown/peanut-brittle-recipe-1914388) using `scraper`.
When I try to parse the website however, I get a "not yet implemented" error on, I think, the `get_template_contents` function.

Is this error expected? I couldn't find anything obvious in the documentation about features missing, or that this kind of error might come up. I'm not sure whether there is something I am doing wrong, or something I can do to avoid this error.

If there's anything I can do to test further or help out to fix it, please let me know. I'm keen to help. 

Thanks in advance!

A minimal way to reproduce the error is:

    extern crate reqwest;
    extern crate scraper;

    use scraper::Html;

    fn main() {
        let url_text = reqwest::get("https://www.foodnetwork.com/recipes/alton-brown/peanut-brittle-recipe-1914388").unwrap().text().unwrap();          
        let _doc = Html::parse_document(url_text.as_str());
    }

Backtrace when running `RUST_BACKTRACE=1 cargo run` is:

	######@########:~/code/test_select$ RUST_BACKTRACE=1 cargo run
	    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
	     Running `target/debug/test_select`
	thread 'main' panicked at 'not yet implemented', /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/scraper-0.6.0/src/html/tree_sink.rs:186:9
	stack backtrace:
	   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
		     at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
	   1: std::sys_common::backtrace::print
		     at libstd/sys_common/backtrace.rs:71
		     at libstd/sys_common/backtrace.rs:59
	   2: std::panicking::default_hook::{{closure}}
		     at libstd/panicking.rs:211
	   3: std::panicking::default_hook
		     at libstd/panicking.rs:227
	   4: std::panicking::rust_panic_with_hook
		     at libstd/panicking.rs:511
	   5: std::panicking::begin_panic
		     at /checkout/src/libstd/panicking.rs:445
	   6: scraper::html::tree_sink::<impl markup5ever::interface::tree_builder::TreeSink for scraper::html::Html>::get_template_contents
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/scraper-0.6.0/src/html/tree_sink.rs:186
	   7: <html5ever::tree_builder::TreeBuilder<Handle, Sink>>::appropriate_place_for_insertion
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tree_builder/mod.rs:373
	   8: <html5ever::tree_builder::TreeBuilder<Handle, Sink>>::insert_element
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tree_builder/mod.rs:1177
	   9: <html5ever::tree_builder::TreeBuilder<Handle, Sink>>::insert_element_for
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tree_builder/mod.rs:1210
	  10: <html5ever::tree_builder::TreeBuilder<Handle, Sink>>::step
		     at ./target/debug/build/html5ever-3104504867a7d440/out/rules.rs:353
	  11: <html5ever::tree_builder::TreeBuilder<Handle, Sink>>::process_to_completion
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tree_builder/mod.rs:312
	  12: <html5ever::tree_builder::TreeBuilder<Handle, Sink> as html5ever::tokenizer::interface::TokenSink>::process_token
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tree_builder/mod.rs:474
	  13: <html5ever::tokenizer::Tokenizer<Sink>>::process_token
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tokenizer/mod.rs:232
	  14: <html5ever::tokenizer::Tokenizer<Sink>>::emit_current_tag
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tokenizer/mod.rs:425
	  15: <html5ever::tokenizer::Tokenizer<Sink>>::step
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tokenizer/mod.rs:628
	  16: <html5ever::tokenizer::Tokenizer<Sink>>::run
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tokenizer/mod.rs:361
	  17: <html5ever::tokenizer::Tokenizer<Sink>>::feed
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/tokenizer/mod.rs:219
	  18: <html5ever::driver::Parser<Sink> as tendril::stream::TendrilSink<tendril::fmt::UTF8>>::process
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.3/src/driver.rs:88
	  19: tendril::stream::TendrilSink::one
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.4.0/src/stream.rs:47
	  20: scraper::html::Html::parse_document
		     at /home/########/.cargo/registry/src/github.com-1ecc6299db9ec823/scraper-0.6.0/src/html/mod.rs:55
	  21: test_select::main
		     at src/main.rs:8
	  22: std::rt::lang_start::{{closure}}
		     at /checkout/src/libstd/rt.rs:74
	  23: std::panicking::try::do_call
		     at libstd/rt.rs:59
		     at libstd/panicking.rs:310
	  24: __rust_maybe_catch_panic
		     at libpanic_unwind/lib.rs:105
	  25: std::rt::lang_start_internal
		     at libstd/panicking.rs:289
		     at libstd/panic.rs:374
		     at libstd/rt.rs:58
	  26: std::rt::lang_start
		     at /checkout/src/libstd/rt.rs:74
	  27: main
	  28: __libc_start_main
	  29: _start

**Comment by programble** [comment]
Yeah sorry, I had left it unimplemented because I wasn't sure how it was meant to work, but reading the documentation now it seems straightforward enough. I'll work on a fix.

**Comment by programble** [comment]
Released in 0.7.0
