### ISSUE TITLE
Allow configuration of html5ever::driver::ParseOpts

### ISSUE THREAD

**Issue by ticky** [programble/scraper#12]
Currently, it doesn’t appear to be possible to configure how html5ever’s parser is configured.

This is mostly okay but if you want to override `scripting_enabled` or other such settings you can’t right now!

**Comment by programble** [comment]
I'm not sure if `Html::parse_document` and `parse_fragment` should take `ParseOpts`. How many calls would pass something other than `Default::default()`? Without it, I think you could call the html5ever parser directly:

```rust
let parser = html5ever::driver::parse_document(scraper::Html::new_document(), parse_opts);
let doc = parser.one(html_string);
```
