### ISSUE TITLE
Consider adding support for reading attributes from ElementRef

### ISSUE THREAD

**Issue by pkozelka** [programble/scraper#15]
Right now, I can use attributes in the query string, but when I locate the node that I want, I have no chance to read its attributes or iterate over them. Not even HTML node ID can be read.
Or am I missing something?

(BTW thanks for the great work!)

**Comment by programble** [comment]
The [`value`](https://docs.rs/scraper/0.9.0/scraper/element_ref/struct.ElementRef.html#method.value) method on `ElementRef` returns the `Element` which has `id`, `attr` and `attrs` [methods](https://docs.rs/scraper/0.9.0/scraper/node/struct.Element.html#methods).

There is an example here <https://docs.rs/scraper/0.9.0/scraper/#accessing-element-attributes>.

**Comment by pkozelka** [comment]
cool, thanks!
