### ISSUE TITLE
Question: how can I use prev_sibling_element?

### ISSUE THREAD

**Issue by pkozelka** [programble/scraper#16]
Is there a way to access method `prev_sibling_element()`?
It seems to be defined inside a private module so it is not accessible.

I need to traverse HTML where the elements are organized in a long list, pairs of `<h4>` with title and `<div>` with content, both of which I need to read.

**Comment by programble** [comment]
You mean [this method](https://github.com/programble/scraper/blob/master/src/element_ref/element.rs#L29)? It's part of a [public trait](https://docs.rs/selectors/0.20.0/selectors/trait.Element.html) of `selectors` so you need to `use selectors::Element;`.

**Comment by pkozelka** [comment]
Thanks for the pointers! I was a bit confused by trying to use `scraper::selectors`. Now after adding separate dependency on `selectors = "0.20.0"` it works exactly as you describe.
Troubles of RUST beginner... thank you again!
