### ISSUE TITLE
Selector can not capture <tr></tr>.

### ISSUE THREAD

**Issue by kenkoooo** [programble/scraper#24]
As the example, the following code works correctly.
```rust
use scraper::{Html, Selector};
fn main() {
    let html = r#"
    <ul>
        <li>Foo</li>
        <li>Bar</li>
        <li>Baz</li>
    </ul>
"#;

    let fragment = Html::parse_fragment(html);
    let selector = Selector::parse("ul").unwrap();
    assert!(fragment.select(&selector).next().is_some());
}
```

Although the following code is almost same as the above one, it doesn't work.
```rust
use scraper::{Html, Selector};
fn main() {
    let html = r#"
    <tr>
        <li>Foo</li>
        <li>Bar</li>
        <li>Baz</li>
    </tr>
"#;

    let fragment = Html::parse_fragment(html);
    let selector = Selector::parse("tr").unwrap();
    assert!(fragment.select(&selector).next().is_some());
}
```

**Comment by kenkoooo** [comment]
I found not only `tr`, but also `td`, `col`, `th` are disabled.

**Comment by programble** [comment]
Those elements are not allowed outside of `<table>`, so it seems `html5ever` throws them out. These work fine when parsing a `<table>`.

**Comment by kenkoooo** [comment]
I see. Thank you for your quick response!

**Comment by deft01** [comment]
I think this should at least trigger a `log::warn` ? Since it is difficult to debug without it.

I don't know if a handle on this `html5ever` error event can be made or still exist. Will have a look if I have the time.
