### ISSUE TITLE
Put an example in the README

### ISSUE THREAD

**Issue by svenstaro** [programble/scraper#25]
I find it helps a lot to quickly judge a library on how it's intended to be used if the author presents a simple example on the README.

**Comment by programble** [comment]
There are a number of examples in the module documentation, where they can be tested. There's always this problem with Rust crates where it doesn't make much sense to put anything in the README and yet crates.io surfaces it. I suppose I should use [cargo-readme](https://crates.io/crates/cargo-readme) and just ignore the duplication.

**Comment by svenstaro** [comment]
Very nice! Thanks.
