### ISSUE TITLE
A way to get innerHTML or innerText?

### ISSUE THREAD

**Issue by Typhox-** [programble/scraper#3]
I haven't found any function like this in the Documentation. When dealing with &lt;br&gt; elements, it would be really handy if there was a way to just get the innerText or at least innerHTML of a NodeRef.

**Comment by programble** [comment]
It seems hard to specify what such functions really do. Would iterating over children and filtering with `Node::is_text` not do enough?

**Comment by Typhox-** [comment]
Yes, this is what I'm currently doing, but a shortcut like in Javascript would be pretty handy as it is quite a common use case.

**Comment by programble** [comment]
The problem with the former is that there is currently no way to serialize the HTML tree back into valid HTML text. The latter would require allocation, which I'd rather not do when there is an iterator available.

**Comment by Typhox-** [comment]
Ah ok I see the problem. Thanks anyway.

**Comment by programble** [comment]
Keeping this issue open since I think it might be good to have a convenience iterator for text.

**Comment by programble** [comment]
Text iterator added in `v0.3.0`: https://cmcenroe.me/scraper/scraper/index.html#accessing-descendent-text.

**Comment by programble** [comment]
`ElementRef::inner_html` added by #6.

**Comment by bergkvist** [comment]
## Basic scraper::ElementRef::inner_text() implementation
```rust
trait InnerText {
    fn inner_text(&self) -> String;
}

impl InnerText for scraper::ElementRef<'_> {
    fn inner_text(&self) -> String {
        self.text()
            .fold("".to_string(), |l, r| format!("{}{}", l, r))
    }
}
```

## A simple test showing expected behavior
All element tags are removed
```rust
let fragment = scraper::Html::parse_fragment(r#"
    <div>stuff <a>link</a> other<br></br> stuff</div>
"#);

let div_selector = scraper::Selector::parse("div").unwrap();
let first_div = fragment.select(&div_selector).nth(0).unwrap();

assert_eq!(
    first_div.inner_text(),
    "stuff link other stuff"
)
```

**Comment by causal-agent** [comment]
You can just call `self.text().collect()`
