### ISSUE TITLE
Fetch Dynamic Pages

### ISSUE THREAD

**Issue by fabiodcorreia** [programble/scraper#32]
Hi,

It's possible to fetch page that are rendered dynamically like Angular or React? In my case I want to wait until the page loads completely but one table is loaded dynamically after receive the result of an API call.

Best Regards

**Comment by programble** [comment]
No, scraper only deals with static HTML. What you mention would require an entire JS engine / headless browser to function.

If some data is loaded from an API call, can you not perform the API call directly yourself?

**Comment by fabiodcorreia** [comment]
That's what I end up doing, but the idea of having a JS engine attached to the HTML it's very nice but probably very hard to implement.
