### ISSUE TITLE
Ability to specify attribute constraints in selectors

### ISSUE THREAD

**Issue by msfjarvis** [programble/scraper#35]
Python's BeautifulSoup library allows to match based on both the tag as well as attributes. For example, in this HTML fragment

```html
<a href="/contact" target="_blank">Contact</a>
<a href="/about">About</a>
```
Using `Selector::parse("a").unwrap()` as the selector would return both of these elements, but BeautifulSoup's `soup.find_all("a", attrs={"target":"_blank"})` would only return the first one. This can probably be handled at the user end but a proper API within the crate, if possible, would greatly alleviate friction in porting Python scraping code over to Rust.

**Comment by programble** [comment]
This can be done with [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), for example `a[target="_blank"]`.
